#!/bin/bash

#This program will check system usage and send alert if needed

# Let user know something is happening
echo "Free memory check starting"
echo " "

# enter admin email
email="ebaxter1@hawk.iit.edu"

# Put usage into variable
usage=`cat /proc/meminfo | grep MemFree | awk '{print $2}'`

# echo $usage

# check usage
check=1
while [ $check = 1 ]
do
if [ $usage -lt 1000000 ] 
then
	mailx -s "Free Cashed Memory Drop Warning!!" $email < warningMessage2
	echo "Free Cached Memory has dropped below 1000MB. Email alert sent to system administrator, please check email for more information."
	echo "Program will now close to prevent multiple emails. Please start program again to resume monitering" 
	check=0
else
	check=1
	sleep 10
fi
# make it so program stops sometimes
sleep 1

done

exit 0
