#!/bin/bash
#This program will find the element that is listed an odd number of times
#

echo "Hello and welcome to the odd count program!"
echo " "

#variables
a1=(1 1 2 2 3 3 4 4 5 5 6 7 7 7 7)
a2=(10 10 7 7 6 6 2 2 3 3 4 4 5 5 6 7 7 7 7 10 10)
a3=(6 6 10 10 7 7 6 6 2 2 3 3 4 4 5 5 6 7 7 7 7 10 10)
a4=(10 10 7 7 2 2 3 3 4 4 5 5 7 7 7 7 10 10 6)
a5=(6 6)
a6=(1)

function findOddCount () 
{
	#echo $@ | grep -o 7 | wc -l
	# echo $@ | tr " " "\n" | sort | uniq -c | cut -d" " -f7,8
	values=( $(echo $@ | tr " " "\n" | sort | uniq -c | cut -d" " -f7) )
	oddNum=""
	keys=( $(echo $@ | tr " " "\n" | sort | uniq -c | cut -d" " -f8) )
	count=0
	# echo ${values[@]}
	for i in "${keys[@]}"; do
		# echo $i
		valueNum=`echo ${values[$count]}`
		# echo $valueNum
		checkNum=$((valueNum % 2))
		# echo $checkNum
		if [ "$checkNum" != 0 ]
		then
			
		 	oddNum=$i
			echo $oddNum
		fi
		count=$((count + 1))	
	done 
	if [ "$oddNum" = "" ]
	then
		#yes="yes"
		echo "unable to be found"
	fi
	
}


#calls
# findOddCount ${a2[@]}
echo -n "odd value in a1 is "; findOddCount ${a1[@]}
echo " "
echo -n "odd value in a2 is "; findOddCount ${a2[@]}
echo " "
echo -n "odd value in a3 is "; findOddCount ${a3[@]}
echo " "
echo -n "odd value in a4 is "; findOddCount ${a4[@]}
echo " "
echo -n "odd value in a5 is "; findOddCount ${a5[@]}
echo " "
echo -n "odd value in a6 is "; findOddCount ${a6[@]}
echo " "



echo "That is all arrays! Program closing"

exit 0
