#!/bin/bash
#This program will display a different message based on what the current time is

TIME=`date | tr " " ":" | cut -d: -f4`
#echo "Enter number:"
#read TIME

if [ $TIME -ge 0 -a $TIME -lt 12 ]
then
	echo "Good Morning"
elif [ $TIME -ge 12 -a $TIME -lt 17 ]
then
	echo "Good Afternoon"
else 
	echo "Good Evening"
fi

exit 0
