#!/bin/bash

# This program will kill all current sleep processes

echo "Welcome to the kill sleep process program"
echo " "

# checks to see if there are any sleep process
echo "Running search for sleep processes"
pgrep sleep > /dev/null 2>&1

# will try and end any sleep process
if [ $? -ne 0 ] 
then
	echo "There are currently no sleep processes"
	echo "Program now ending"
else
	pkill "^sleep$" > /dev/null 2>&1
	echo " "
	echo "The following sleep process have been killed. Goodbye"
fi

exit 0
