#!/bin/bash

# This program will check how many times a user is logged on

echo "Welcome to the login check program"

# global variables
name=" "

# grab uid
function getUID () {

echo " "
echo "Please enter the UID of the user you would like to check the logins for:"
read name

}
